### ISSUE TITLE
import mapboxgl from '../mapbox'  not found

### ISSUE THREAD

**Issue by goodcesium** [jiegiser/mapbox_example#2]
import mapboxgl from '../mapbox'  not found

**Comment by snowisland1** [comment]
+1

**Comment by jiegiser** [comment]
> import mapboxgl from '../mapbox' not found

已加，，，这就是一个 accessToken 。。也没啥。看代码也能知道少了什么。。这个项目例子没几个，，很少

**Comment by jiegiser** [comment]
1
